### ISSUE TITLE
data cannot be downloaded

### ISSUE THREAD

**Issue by eduOS** [suriyadeepan/practical_seq2seq#13]
Hi, it seems that dropbox has prevented the data downloading due to the too much traffic generated by this. Can we get the data elsewhere?
Thanks.

**Comment by suriyadeepan** [comment]
which data are we talking about?

**Comment by eduOS** [comment]
I mean the data via this link: https://www.dropbox.com/s/tmfwptbs3q180p0/seq2seq.twitter.tar.gz?dl=0

**Comment by suriyadeepan** [comment]
i've added it to the repo directly - [seq2seq.twitter.tar.gz](https://github.com/suriyadeepan/practical_seq2seq/blob/master/datasets/twitter/seq2seq.twitter.tar.gz)
