### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by nicks165** [suriyadeepan/practical_seq2seq#15]
I know it might be a v silly question but i am trying to get my hands on this seq2seq model. 
I am trying to run 
python 03-Twitter-chatbot.py
It is doing the training again right? 
As you already provided a checkpoint. So how should i use it ? Is there a way to validate/test ?

**Comment by suriyadeepan** [comment]
I have intentionally left it out. This [notebook](https://github.com/suriyadeepan/practical_seq2seq/blob/master/03-Twitter-chatbot.ipynb) should give you some insights.
