### ISSUE TITLE
Restore training clarification

### ISSUE THREAD

**Issue by jonaslund** [suriyadeepan/practical_seq2seq#2]
Hey

Great seq2seq examples! 

To clarify, to continue training after an interruption.

```python
sess = model.train(train_batch_gen, val_batch_gen)
# to continue training after interrupting,
#  run model.train with "sess=sess"
```

means to continue like this?

```python
sess = model.restore_last_session()
sess.train(train_batch_gen, val_batch_gen)
```

thx!

**Comment by suriyadeepan** [comment]
thanks @jonaslund

```python
# restore last saved session from checkpoint folder and return it
sess = model.restore_last_session() 
# pass session as an argument to train method
model.train(train_batch_gen, val_batch_gen, sess=sess) 
```

**Comment by jonaslund** [comment]
Just found it... but thanks for clarifying!
👍

**Comment by Jatapiaro** [comment]
It doesnt work, The count starts from the beggining, I just got the same file with some template text append at the end

**Comment by Jatapiaro** [comment]
@jonaslund Did that works for you? I mean if you're are in checkpoint 3000, and you stoped training and restart it, your next checkpoint is 4000? When I do that and obviously passing as argument the session, and restoring it, it starts from the beginning.
