### ISSUE TITLE
Python3 or Python2

### ISSUE THREAD

**Issue by gaopeng-eugene** [suriyadeepan/practical_seq2seq#3]
File "03-Twitter-chatbot.py", line 12, in <module>
    metadata, idx_q, idx_a = data.load_data(PATH='datasets/twitter/')
  File "/opt/data/practical_seq2seq/datasets/twitter/data.py", line 206, in load_data
    metadata = pickle.load(f)
  File "/usr/lib/python2.7/pickle.py", line 1378, in load
    return Unpickler(file).load()
  File "/usr/lib/python2.7/pickle.py", line 858, in load
    dispatch[key](self)
  File "/usr/lib/python2.7/pickle.py", line 886, in load_proto
    raise ValueError, "unsupported pickle protocol: %d" % proto
ValueError: unsupported pickle protocol: 3

**Comment by gaopeng-eugene** [comment]
Will you provide the training code? By the way, please clarify your model are trained by python 3 or python 2. If you use python 3, can you provide a model compatible with python 2.
Please check this http://stackoverflow.com/questions/29587179/load-pickle-filecomes-from-python3-in-python2

**Comment by suriyadeepan** [comment]
@gaopeng-eugene I have provided the [training code](https://github.com/suriyadeepan/practical_seq2seq/blob/master/03-Twitter-chatbot.py). Yes, I have used python 3 (will mention that in README now). I know pickle is incompatible with cPickle. I really don't want to make my code compatible with python 2. It will open up a whole new can of worms. You should consider upgrading to python 3.
