### ISSUE TITLE
Predict with specific terms

### ISSUE THREAD

**Issue by jonaslund** [suriyadeepan/practical_seq2seq#4]
Hi

I was wondering if there's a straight forward way to the trained models to predict answers for specific terms / questions. 

Since the model.predict takes encoded data, which is then decoded. Did you work out a method to encode sentences on the fly to get an interactive mode running?

Thx again

**Comment by suriyadeepan** [comment]
You can use some of the functions from this [module](https://raw.githubusercontent.com/suriyadeepan/tweet_bot/master/data_utils.py). If you are interested in deploying the trained model to chat with users (without having to reinvent the wheel), you might wanna resuse some of the code from this [repository](https://github.com/suriyadeepan/tweet_bot). Specifically [data_utils.py](https://github.com/suriyadeepan/tweet_bot/blob/master/data_utils.py) and [chatbot.py](https://github.com/suriyadeepan/tweet_bot/blob/master/chatbot.py).

**Comment by jonaslund** [comment]
Brilliant. Thanks
