### ISSUE TITLE
How to convert this chat bot to technical bot ?

### ISSUE THREAD

**Issue by phpmind** [suriyadeepan/practical_seq2seq#8]
Hi suriyadeepan,

How can i use this chat bot to query from the database on demand and based on show result. 

Basically, I am looking for something like API.AI like feature, where I can add intend and entities and based on that i can query. 

Can you please guide me?

Thanks

**Comment by suriyadeepan** [comment]
You can't. Generative chatbots are still in experimental phase. A [retrieval-based](http://www.wildml.com/2016/07/deep-learning-for-chatbots-2-retrieval-based-model-tensorflow/) model is what you are looking for.

**Comment by phpmind** [comment]
suriyadeepan@ I agree with you but if you look at API.AI, WIT.AI and MicrosoftBot they all have some kind of features to convert chat bot into any tech bot. A limitation is they store data customer and in my case, it is not possible to use them. 

chatterbot is another example but chatterbot is not using seq2seq or either tensorflow. 

http://chatterbot.readthedocs.io/en/stable/

Thanks
